package app.view;

import app.controladores.ArbolController;
import app.core.models.NodoBinario;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import java.awt.*;
import java.util.List;
import java.util.Map;

public class ArbolExpresionForm {
    public JPanel PanelPrincipal;
    private JLabel LblTitulo;
    private JLabel LblSubtitulo;
    private JLabel LblValor;
    private JTextField txtDatos;
    private JButton btnInsertar;
    private JButton btnAltura;
    private JButton btnNiveles;
    private JButton btnRecorridos;
    private JLabel lblConsola;
    private JTree ViewArbol;
    private JButton btnLimpiar;
    private JTextArea txtConsola;

    private ArbolController controller;

    public ArbolExpresionForm(ArbolController controller) {
        this.controller = controller;
        PanelPrincipal.setPreferredSize(new Dimension(900, 600));
        ViewArbol.setModel(null);
        btnInsertar.addActionListener(e -> agregar());
        txtDatos.addActionListener(e -> agregar()); // ENTER ejecuta también

        btnAltura.addActionListener(e -> altura());
        btnNiveles.addActionListener(e -> niveles());
        btnRecorridos.addActionListener(e -> recorridos());
        btnLimpiar.addActionListener(e -> limpiar());
    }

    private void agregar() {

        String expresion = txtDatos.getText().trim();

        if (expresion.isBlank()) {
            mostrar("Ingrese una expresion valida.");
            return;
        }

        try {
            controller.construirExpresion(expresion);

            actualizarArbol();

            double resultado = controller.evaluarExpresion();

            mostrar("Expresion construida correctamente.");
            mostrar("Resultado de la expresion: " + resultado);

            txtDatos.setText("");

        } catch (Exception ex) {
            mostrar("Error en la expresion: " + ex.getMessage());
        }
    }

    private void actualizarArbol() {

        NodoBinario<String> raiz = controller.getRaizExpresion();

        if (raiz == null) {
            ViewArbol.setModel(null);
            return;
        }

        DefaultMutableTreeNode root = construirNodoVisual(raiz);

        ViewArbol.setModel(new DefaultTreeModel(root));
        expandirTodo();
    }

    private void expandirTodo() {
        for (int i = 0; i < ViewArbol.getRowCount(); i++) {
            ViewArbol.expandRow(i);
        }
    }

    private DefaultMutableTreeNode construirNodoVisual(NodoBinario<String> nodo) {

        DefaultMutableTreeNode visual =
                new DefaultMutableTreeNode(nodo.getDato());

        if (nodo.getIzquierdo() != null)
            visual.add(construirNodoVisual(nodo.getIzquierdo()));

        if (nodo.getDerecho() != null)
            visual.add(construirNodoVisual(nodo.getDerecho()));

        return visual;
    }

    private void altura() {

        if (controller.estaVacioExpresion()) {
            mostrar("El arbol esta vacio.");
            return;
        }

        int h = controller.getAlturaExpresion();
        mostrar("Altura: " + h);
    }

    private void niveles() {

        if (controller.estaVacioExpresion()) {
            mostrar("El arbol esta vacio.");
            return;
        }

        Map<Integer, List<String>> niveles =
                controller.getNivelesExpresion();

        StringBuilder sb = new StringBuilder();

        niveles.forEach((nivel, lista) -> {
            sb.append("Nivel ")
                    .append(nivel)
                    .append(": ")
                    .append(lista)
                    .append("\n");
        });

        mostrar(sb.toString());
    }

    private void recorridos() {

        if (controller.estaVacioExpresion()) {
            mostrar("El arbol esta vacio.");
            return;
        }

        Object[] opciones = {"Preorden", "Inorden", "Postorden"};

        int eleccion = JOptionPane.showOptionDialog(
                PanelPrincipal,
                "Seleccione recorrido",
                "Recorridos",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                opciones,
                opciones[0]
        );

        if (eleccion == -1) return;

        switch (eleccion) {
            case 0 -> mostrar(controller.getPreordenExpresion().toString());
            case 1 -> mostrar(controller.getInordenExpresion());
            case 2 -> mostrar(controller.getPostordenExpresion().toString());
        }
    }

    private void limpiar() {

        controller.reset();
        ViewArbol.setModel(null);
        txtConsola.setText("Arbol de expresion reiniciado.");
    }

    private void mostrar(String mensaje) {
        txtConsola.append(mensaje + "\n");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PanelPrincipal = new JPanel();
        PanelPrincipal.setLayout(new GridLayoutManager(13, 3, new Insets(0, 0, 0, 0), -1, -1));
        LblTitulo = new JLabel();
        LblTitulo.setText("Arbol de Expresiones");
        PanelPrincipal.add(LblTitulo, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblConsola = new JLabel();
        lblConsola.setText("Consola");
        PanelPrincipal.add(lblConsola, new GridConstraints(11, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        LblSubtitulo = new JLabel();
        LblSubtitulo.setText("Representacion VIsual");
        PanelPrincipal.add(LblSubtitulo, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        LblValor = new JLabel();
        LblValor.setText("Ingresa tu expresion:");
        PanelPrincipal.add(LblValor, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtDatos = new JTextField();
        PanelPrincipal.add(txtDatos, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        PanelPrincipal.add(scrollPane1, new GridConstraints(12, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        txtConsola = new JTextArea();
        scrollPane1.setViewportView(txtConsola);
        final JScrollPane scrollPane2 = new JScrollPane();
        PanelPrincipal.add(scrollPane2, new GridConstraints(4, 0, 7, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        ViewArbol = new JTree();
        scrollPane2.setViewportView(ViewArbol);
        btnInsertar = new JButton();
        btnInsertar.setText("Agregar");
        PanelPrincipal.add(btnInsertar, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnAltura = new JButton();
        btnAltura.setText("Calcular Altura");
        PanelPrincipal.add(btnAltura, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnNiveles = new JButton();
        btnNiveles.setText("Niveles");
        PanelPrincipal.add(btnNiveles, new GridConstraints(6, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRecorridos = new JButton();
        btnRecorridos.setText("Recorridos");
        PanelPrincipal.add(btnRecorridos, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnLimpiar = new JButton();
        btnLimpiar.setText("Limpiar");
        PanelPrincipal.add(btnLimpiar, new GridConstraints(8, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelPrincipal;
    }

}
